var dataHome = '<div id="paper">'
    + '<script id="template" type="text/x-handlebars-template">'
	+ '<h1>{{header}}</h1>'
	+ '<img id = "Toma" src="photos/Toma2.jpg" width="180" height="170" alt="">'
	+ '<h2><b>{{fio}}</b></h2>'
	+ '<p>{{aboutFio}}</p>'
+ ''
    + '<h2>{{Moscow}}</h2>'
    + '<img src="photos/Moscow.jpg" width="240" height="180" alt="">'
    + '<p>{{aboutMoscow}}</p>'
    + '<ul>'
        + '<li><a href="https://vk.com/album19716213_0" target="_blank">{{moreMoscow}}</a></li>'
        + '<li><a href="https://www.youtube.com/watch?v=KATwPIiR8Lg" target="_blank">{{evenMoreMoscow}}</a></li>'
    + '</ul>'
+ ''
    + '<h2>{{Petersburg}}</h2>'
    + '<img src="photos/Piter2.jpg" width="240" height="180" alt="">'
    + '<p>{{aboutPetersburg}}</p>'
    + '<ul>'
        + '<li><a href="https://vk.com/album19716213_0" target="_blank">{{morePetersburg}}</a></li>'
        + '<li><a href="https://www.youtube.com/watch?v=VDVoEOEgq9A" target="_blank">{{evenMorePetersburg}}</a></li>'
    + '</ul>'
+ ''
    + '<h2>{{Saransk}}</h2>'
    + '<img src="photos/Saransk2.jpg" width="240" height="180" alt="">'
    + '<p>{{aboutSaransk}}</p>'
    + '<ul>'
        + '<li><a href="https://vk.com/album19716213_0" target="_blank">{{moreSaransk}}</a></li>'
        + '<li><a href="https://www.youtube.com/watch?v=rs7aVehrn-4" target="_blank">{{evenMoreSaransk}}</a></li>'
    + '</ul>'
    + '</script>'
+ '</div>'

