var dataPageHome = [{
      id: 'en',
      header: 'Your personal photographer in Russia',
      fio: 'Kurguzova Tamara',
      aboutFio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde amet quibusdam eius inventore expedita, qui eveniet quia beatae. Quam adipisci cumque iusto quidem, nulla repellat architecto recusandae culpa accusantium, assumenda, ipsum minus iure alias nam optio quisquam in facilis, fugit eius pariatur quaerat unde. Dolore, aut omnis quibusdam ipsam! Ratione!',
      Moscow: 'Moscow',
      aboutMoscow: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      moreMoscow:'mo`re Moscow',
      evenMoreMoscow: 'even more Moscow',
      Petersburg: 'St. Petersburg',
      aboutPetersburg: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      morePetersburg: 'more St. Petersburg',
      evenMorePetersburg: 'even more St. Petersburg',
      Saransk: 'Saransk (Mordovia)',
      aboutSaransk: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      moreSaransk: 'more Saransk',
      evenMoreSaransk: 'even more Saransk'
   },
   {
      id: 'ru',
      header: 'Ваш персональный фотограф в России',
      fio: 'Kurguzova Tamara',
      aboutFio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde amet quibusdam eius inventore expedita, qui eveniet quia beatae. Quam adipisci cumque iusto quidem, nulla repellat architecto recusandae culpa accusantium, assumenda, ipsum minus iure alias nam optio quisquam in facilis, fugit eius pariatur quaerat unde. Dolore, aut omnis quibusdam ipsam! Ratione!',
      Moscow: 'Moscow',
      aboutMoscow: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      moreMoscow: 'more Moscow',
      evenMoreMoscow: 'even more Moscow',
      Petersburg: 'St. Petersburg',
      aboutPetersburg: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      morePetersburg: 'more St. Petersburg',
      evenMorePetersburg: 'even more St. Petersburg',
      Saransk: 'Saransk (Mordovia)',
      aboutSaransk: 'We spent our last three days in London in a cool apartment in Lambeth. We saw some of the main attractions, but there\'s no way to squeeze them all in in three days&#8212;at least not enjoyably. We had a great time at the Tower of London. The British Museum was amazing, but we didn\'t have nearly enough time there. Cary particularly enjoyed the Cabinet War Rooms and Museum. We saw Les Miserables as well as Othello at the Globe, and we ate great food.',
      moreSaransk: 'more Saransk',
      evenMoreSaransk: 'even more Saransk'
   }
   ];
