var menuHeader = '<div id="lang_selector" class="language-dropdown">'
	  + '<label for="toggle" class="lang-flag lang-ru" title="Click to select the language">'
	    + '<span class="flag"></span>'
	  + '</label>'
	  + ''
	  + '<ul class="lang-list">'
	    + '<li class="lang lang-ru selected" title="RU">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-ch" title="CH">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-in" title="IN">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-jp" title="JP">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-ko" title="KO">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-ind" title="IND">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-th" title="TH">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-tu" title="TU">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-sa" title="SA">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-en" title="EN">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-fr" title="FR">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-ge" title="GE">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-sp" title="SP">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-po" title="PO">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-is" title="IS">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-it" title="IT">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-cz" title="CZ">'
	      + '<span class="flag"></span>'
	    + '</li>'
	    + '<li class="lang lang-pol" title="POL">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   	+ '<li class="lang lang-se" title="SE">'
	      + '<span class="flag"></span>'
	    + '</li>'
	   + '</ul>'
	+ '</div>'
+ ''
	+ '<div id="si" class="social-icons icon-circle icon-rotate list-unstyled list-inline">'
		+ '<a id="drugayaplaneta" href="https://vk.com/drugayaplaneta" target="_blank"><i class="fa fa-vk fa-3x planeta inblck"></i></a><br>'
		+ '<a href="https://www.instagram.com/drugayaplaneta" target="_blank"><i class="fa fa-instagram fa-3x inblck"></i></a><br>'
	 	+ '<a href="http://drugayaplaneta.tumblr.com/" target="_blank"><i class="fa fa-globe fa-3x inblck"></i></a><br>'
	 	+ '<a href="https://www.facebook.com/profile.php?id=100015967323198" target="_blank"><i class="fa fa-facebook fa-3x inblck"></i></a><br>'
	 	+ '<a href="https://vk.com/id19716213" target="_blank"><i class="fa fa-vk fa-3x inblck"></i></a><br>'
	+ '</div>'
