var menuHeader = '	<ul id="menu-bar">'
		+ '<li><a href="index.html">Главная</a></li>'
		+ '<li><a href="portfolio.html">Портфолио</a></li>'
		+ '<li><a href="about.html">О себе</a></li>'
		+ '<!--<li><a href="#">Products</a>'
		+ '<ul>'
		+ '<li><a href="#">Products Sub Menu 1</a></li>'
		+ '<li><a href="#">Products Sub Menu 2</a></li>'
		+ '<li><a href="#">Products Sub Menu 3</a></li>'
		+ '<li><a href="#">Products Sub Menu 4</a></li>'
		+ '</ul>'
		+ '</li>'
		+ '<li><a href="#">Services</a>'
		+ '<ul>'
		+ '<li><a href="#">Services Sub Menu 1</a></li>'
		+ '<li><a href="#">Services Sub Menu 2</a></li>'
		+ '<li><a href="#">Services Sub Menu 3</a></li>'
		+ '<li><a href="#">Services Sub Menu 4</a></li>'
		+ '</ul>'
		+ '</li>-->'
		+ '<i id = "glbl" class="fa fa-globe fa-3x icon-rotate" aria-hidden="true"></i>'
	+ '</ul>'
	+ '<div id="si" class="social-icons icon-circle icon-rotate list-unstyled list-inline">'
		+ '<a id="drugayaplaneta" href="https://vk.com/drugayaplaneta" target="_blank"><i class="fa fa-vk fa-3x inblck"></i></a><br>'
		+ '<a href="https://www.instagram.com/drugayaplaneta" target="_blank"><i class="fa fa-instagram fa-3x inblck"></i></a><br>'
	 	+ '<a href="http://drugayaplaneta.tumblr.com/" target="_blank"><i class="fa fa-globe fa-3x inblck"></i></a><br>'
	 	+ '<a href="https://www.facebook.com/profile.php?id=100015967323198" target="_blank"><i class="fa fa-facebook fa-3x inblck"></i></a><br>'
	 	+ '<a href="https://vk.com/id19716213" target="_blank"><i class="fa fa-vk fa-3x inblck"></i></a><br>'
	+ '</div>'
